name: twitch_hue_bot
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  tmi: ^0.0.4
  hue_dart: ^0.3.0
  color_models: ^1.2.1
  cli_menu: ^0.2.3
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
