name: twitch_hue_bot
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tmi:
    path: dependencies/tmi.dart/
  hue_dart: ^0.3.0
  color_models: ^1.2.1
  cli_menu: ^0.3.0-nullsafety.0
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1
